### ISSUE TITLE
Wrong type def on `getRedisConnectionToken` and `getRedisOptionsToken` parameter

### ISSUE THREAD

**Issue by micalevisk** [nest-modules/ioredis#257]
Here:

https://github.com/nest-modules/ioredis/blob/155a77249a95bcee84b8e87ea101e8588d4e93cb/lib/redis.decorators.ts#L4

`connection` is optional, thus `connection` could be `undefined`.

But here:

https://github.com/nest-modules/ioredis/blob/155a77249a95bcee84b8e87ea101e8588d4e93cb/lib/redis.utils.ts#L13

and here:

https://github.com/nest-modules/ioredis/blob/155a77249a95bcee84b8e87ea101e8588d4e93cb/lib/redis.utils.ts#L9

it's not

Thus, although we can use `@InjectRedis()`, we can't call `getRedisConnectionToken()` (when `"strictNullChecks": true`)

**Comment by juandav** [comment]
DONE
