### ISSUE TITLE
Compatibility with @nestjs/common >= 9.0.0

### ISSUE THREAD

**Issue by stouch** [nest-modules/ioredis#258]
When using @nestjs/common >= 9.0.0 with npm 8, cannot install this lib without forcing --legacy-peer-deps

**Comment by stouch** [comment]
Just for the record, for v9 compatibility, we'll have to use another config format to fit with [@nestjs/microservices](https://docs.nestjs.com/microservices/basics) and [ioredis](https://github.com/luin/ioredis) lib : 

See https://github.com/nestjs/terminus/issues/1288#issuecomment-1189444864 

`url` seems not allowed anymore

**Comment by stouch** [comment]
up 😇

Also seen that NestJS redis docs have changed a lot compared to the previous one (https://docs.nestjs.com/microservices/redis), I don't known how much this gonna affect this repo

**Comment by jonparkdev** [comment]
bump

**Comment by atassis** [comment]
@juandav you have added support for the 9th version of nestjs, but didn't update the package in the npm.

**Comment by vadimoarturo** [comment]
bump

**Comment by srkimir** [comment]
+1

**Comment by pastean** [comment]
is it safe to use by ignoring deps?

**Comment by dzcpy** [comment]
Any updates?

**Comment by srkimir** [comment]
Can somebody please look into this

**Comment by srkimir** [comment]
Get rid of this package finally completely in favour of https://github.com/liaoliaots/nestjs-redis
which supports nest >=9.0.0
migration is quick and easy

**Comment by piyush-kacha** [comment]
> Can somebody please look into this

Code is already updated in main branch just somebody need to update in NPM.

**Comment by vadimoarturo** [comment]
> Get rid of this package finally completely in favour of https://github.com/liaoliaots/nestjs-redis which supports nest >=9.0.0 migration is quick and easy

Will there be an update or can this one be used?

**Comment by juandav** [comment]
The library has already been updated to the latest version.
