### ISSUE TITLE
Typing issue

### ISSUE THREAD

**Issue by zub0r** [nest-modules/ioredis#263]
Doesn't work with nestjs 9 out of the box
![image](https://user-images.githubusercontent.com/2649795/235667524-86adf00e-ac11-406e-b51b-019446af6668.png)

**Comment by imanhpr** [comment]
Any idea? i've got the same problem

**Comment by juandav** [comment]
We couldn't replicate the issue. If it still persists, I invite you to open a new issue, with a complete example on GitHub that I can review.
