### ISSUE TITLE
@InjectRedis decorator incompatible with typescript 5.1.6

### ISSUE THREAD

**Issue by danielsamaniego** [nest-modules/ioredis#267]
I have updated my typescript version from 4.9.5 to 5.1.6 in my NestJs project and @InjectRedis no longer works

```
This is the code:
`@Injectable() export class MyService { 
     constructor( @InjectRedis('REDIS') private readonly redisService: Redis, ) {} 
     ... 
}
```
`

The error I receive is: "Unable to resolve signature of parameter decorator when called as an expression.
Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'."

**Comment by AhmedBHameed** [comment]
Valid issue.

**Comment by wespen** [comment]
Same as https://github.com/nest-modules/ioredis/issues/266

**Comment by juandav** [comment]
The library has already been updated to the latest version.
