### ISSUE TITLE
Peer dependencies

### ISSUE THREAD

**Issue by slukes** [nest-modules/ioredis#268]
Hello,

Please could the peer dependencies be updated for nest 10?

**Comment by stouch** [comment]
#258

**Comment by utkarsh3mehta** [comment]
Hey, 

My nest common is on v10.2.4. According to the issue #258 , v1.0.1 of @node-modules/ioredis should be compatible with v9 as well. But as seen in the screenshot below, I'm unable to install the module. Not just that, the error message also doesn't mention the change for #258 .

I have a feeling i'm doing something silly. Can you please help.

Thanks!

<img width="885" alt="Screenshot 2023-09-10 at 2 37 55 PM" src="https://github.com/nest-modules/ioredis/assets/47495672/d88ed411-ff3c-4bbb-b314-5d3dbcc823b9">

**Comment by juandav** [comment]
The library has already been updated to the latest version.
