### ISSUE TITLE
Issue with Redis module export after reinstalling node_modules

### ISSUE THREAD

**Issue by anassarfraz** [nest-modules/ioredis#279]
### Overview
After deleting th `node_modules` directory and reinstalling it using `npm i --force`, I encountered an issue with the Redis module in `@nestjs-modules/ioredis`. The specific error is as follows:

```typescript
src/redis-cache/redis-cache.service.ts:2:23 - error TS2305: Module '"@nestjs-modules/ioredis"' has no exported member 'Redis'.

2 import { InjectRedis, Redis } from "@nestjs-modules/ioredis";
                        ~~~~~
```
### Steps to Reproduce

1. Delete node_modules directory.
2. Run npm i --force to reinstall dependencies.
3. Attempt to run the NestJS project.

### Expected Behavior
I expected the project to run successfully without any issues related to the `@nestjs-modules/ioredis module`.

### Current Behavior
The project fails to compile with the mentioned TypeScript error regarding the missing exported member 'Redis' in `@nestjs-modules/ioredis`.

### Environment

- Operating System: [e.g., Windows 10, macOS, Linux]
- Node.js version: [`v18.18.2`]
- NPM version: [`9.8.1`]

### @nestjs-modules/ioredis version
- `"@nestjs-modules/ioredis": "^1.0.1",`
- ` "redis": "^3.1.1",`

#### Before delete node modules (file `node_modules/@nestjs-modules/ioredis/dist/redis.interface.d.ts`)
```typescript
import { ModuleMetadata, Type } from '@nestjs/common/interfaces';
import * as Redis from 'ioredis';
export declare type Redis = Redis.Redis;
export interface RedisModuleOptions {
    config: Redis.RedisOptions & {
        url?: string;
    };
}
export interface RedisModuleOptionsFactory {
    createRedisModuleOptions(): Promise<RedisModuleOptions> | RedisModuleOptions;
}
export interface RedisModuleAsyncOptions extends Pick<ModuleMetadata, 'imports'> {
    inject?: any[];
    useClass?: Type<RedisModuleOptionsFactory>;
    useExisting?: Type<RedisModuleOptionsFactory>;
    useFactory?: (...args: any[]) => Promise<RedisModuleOptions> | RedisModuleOptions;
}

```

#### After install node modules (file `node_modules/@nestjs-modules/ioredis/dist/redis.interface.d.ts`)

```typescript

import { ModuleMetadata, Type } from '@nestjs/common/interfaces';
import { RedisOptions } from 'ioredis';
export interface RedisModuleOptions {
    config: RedisOptions & {
        url?: string;
    };
}
export interface RedisModuleOptionsFactory {
    createRedisModuleOptions(): Promise<RedisModuleOptions> | RedisModuleOptions;
}
export interface RedisModuleAsyncOptions extends Pick<ModuleMetadata, 'imports'> {
    inject?: any[];
    useClass?: Type<RedisModuleOptionsFactory>;
    useExisting?: Type<RedisModuleOptionsFactory>;
    useFactory?: (...args: any[]) => Promise<RedisModuleOptions> | RedisModuleOptions;
}

```
### Additional Information

- The issue seems to be related to changes in the redis.interface.d.ts file within @nestjs-modules/ioredis after a fresh installation.
- The issue persists even though there was no explicit version update for @nestjs-modules/ioredis.

I prefer not to update the version of @nestjs-modules/ioredis but seek guidance on resolving the issue without a version change.

### Reproducibility 

- [x]  Always
- [ ]  Often
- [ ]  Sometimes
- [ ]  Rarely
- [ ]  Unable to Reproduce

### Severity 
- [x] High
- [ ]  Medium
- [ ]  Low

### Attachments 
Before and after interface file with same version
![image](https://github.com/nest-modules/ioredis/assets/22854438/ea89bf4c-6a89-4bb8-aa17-bc50f17ac5b0)

Due to changes in interface i am getting in import of redis in my service
![image](https://github.com/nest-modules/ioredis/assets/22854438/d7d27a91-7cb4-4c4e-84a2-0ae9cb87a03a)

Error i am getting
![image](https://github.com/nest-modules/ioredis/assets/22854438/b689282f-ce90-4af7-9097-48a4b9d846ba)

### Additional Notes
I think i am getting these issues after updates in `@nestjs-modules/ioredis` 

### Labels
- `bug`
- `typescript`
- `nestjs`
- `ioredis`
- `redis`

### Assignees
- [@juandav @renovate-bot ]

**Comment by juandav** [comment]
Now you must use it in this way, note that Redis is imported from the 'ioredis' library.

<img width="747" alt="image" src="https://github.com/nest-modules/ioredis/assets/12274145/52516101-e610-4c03-af11-cad6e8364955">

**Comment by anassarfraz** [comment]
@juandav thanks for response
I tried this code with updated version of `@nestjs-modules/ioredis`. it working fine.

I resolved this issue with  remove `^` sign from version number 
("@nestjs-modules/ioredis": "^1.0.1", -------> "@nestjs-modules/ioredis": "1.0.1").

**Comment by juandav** [comment]
@anassarfraz Although you could use the new version of @nestjs-modules/ioredis, version 2.0.1.

**Comment by anassarfraz** [comment]
@juandav yes i used newer version but i got more errors because my nestjs Version 7.0.0 new i am shifting my project to updated packages.
thanks
